# Generated by Django 3.2.9 on 2021-11-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('Masculino', 'male'), ('Feminino', 'female')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=19)),
            ],
        ),
    ]
